

services:
  fase1-cli:
    build: ./fase1
    container_name: fase1-cli
    ports:
      - "8501:8501"


  fase2-db:
    build: ./fase2
    container_name: fase2-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=farmtech
    volumes:
      - pgdata:/var/lib/postgresql/data

  fase3-app:
    build: ./fase3
    container_name: fase3-app
    ports:
      - "8003:8003" # API
      - "8503:8503" # Streamlit
    depends_on:
      - fase2-db

  fase4-db:
    image: postgres:13
    container_name: fase4-db
    volumes:
      - fase4_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 10s
      timeout: 5s
      retries: 5

  fase4-app:
    build: ./fase4
    container_name: fase4-app
    ports:
      - "8004:8004" # API
      - "8504:8504" # Streamlit
    depends_on:
      fase4-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@fase4-db:5432/database

  fase6-app:
    build: ./fase6
    container_name: fase6-app
    volumes:
      - ./fase6:/app
      - ./fase6/input_images:/app/fase6/input_images
      - ./fase6/output_detections:/app/fase6/output_detections

  fase7-app:
    build: ./fase7
    container_name: fase7-app
    ports:
      - "8507:8507"

volumes:
  pgdata:
  fase4_postgres_data:
